### ISSUE TITLE
2个小问题要问

### ISSUE THREAD

**Issue by FXDYJ** [cssxsh/mirai-administrator#13]
1.怎么留言
2.消息审查好像没有，群友都骂街了，没拦截一条
配置文件如下：
```yaml
# 机器人所有者
owner: 3012287203
# 配置项废除, 改为加载 censor 文件夹中的 txt 文件
censor_regex: ''
# 消息审查，类型, IMAGE, FLASH, SERVICE, APP, AUDIO, FORWARD, VIP, MARKET, MUSIC, POKE
censor_types: [ FLASH, SERVICE, APP, AUDIO, FORWARD, VIP, MARKET, MUSIC, POKE]
# 消息审查，禁言时间 单位秒
censor_mute: 300
# 联系人（群/好友/...）聊天记录上限，（用于消息撤销等操作）
record_limit: 100
```
